name: Meeting EPD Server
version: dev
slug: meetingepd
description: The server component for the meetingroom display epd
url: https://github.com/cedi/ical-to-restapi
codenotary: github@cedi.dev
startup: services
ingress: false
init: false
arch:
  - aarch64
map:
  - addon_config

ports:
  8099/tcp: 8099
  50051/tcp: 50051

ports_description:
  8099/tcp: Port used by the REST API
  50051/tcp: Port used by the gRPC API

schema:
  calendars:
    - name: str
      from: list(url)
      ical: str
  server:
    debug: bool?
    refresh: list(5m|15m|30m|1h|4h|8h)
  rules:
    - name: str
      key: str
      contains:
        - str
      skip: bool?

options:
  calendars:
    - name: "calendar1"
      ical: "example.com/calendar/my-ical.ics"
      from: url
  server:
    refresh: 30m
    debug: false
  rules:
    - name: "Skip AllDay Events"
      key: "all_day"
      contains:
        - "true"
      skip: true
    - name: "Skip non-blocking Events"
      key: "busy"
      contains:
        - "Free"
      skip: true
    - name: "Catch All"
      key: "*"
      important: false
      contains:
        - "*"
